# version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      args:
        - NODE_ENV=${VITE_ENV}
    develop:
      watch:
        - path: ./frontend/package.json
          target: /app/package.json
          action: rebuild
        - path: ./frontend
          target: /app
          action: sync
    ports:
      - "80:80"
    environment:
      - NODE_ENV=${VITE_ENV}
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - ./frontend/.env.${VITE_ENV}
    volumes: 
      - ./frontend:/app 
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      args:
        - NODE_ENV=development
    ports:
      # - "${PORT}:${PORT}"
      - "3000:3000"
    volumes: 
      - ./backend:/app 
      - /app/node_modules
    environment:
      - NODE_ENV=development
      # - PORT=${PORT}
      - PORT=3000
    env_file:
      - ./backend/.env

  jenkins: 
    image: jenkins/jenkins:lts 
    ports: 
      - "8080:8080" 
      - "50000:50000" 
    environment: 
      JENKINS_OPTS: "--httpPort=8080" 
    volumes: 
      - jenkins_home:/var/jenkins_home 
      - /var/run/docker.sock:/var/run/docker.sock

volumes: 
  jenkins_home:
