version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    # volumes:
    #   - D:/vuedemo/project:/app
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
